const CONSUMABLES = new Set([
  'item_tpscroll',
  'item_ward_observer',
  'item_ward_sentry',
  'item_clarity',
  'item_tango',
  'item_enchanted_mango',
  'item_faerie_fire',
  'item_smoke_of_deceit',
  'item_dust',
  'item_bottle',
  'item_flask',
  'item_ward_dispenser',
  'item_tome_of_knowledge',
  'item_cheese',
  'item_aegis',
]);

const COMPONENTS = new Set([
  'item_branches',
  'item_circlet',
  'item_slippers',
  'item_mantle',
  'item_band_of_elvenskin',
  'item_robe',
  'item_gauntlets',
  'item_belt_of_strength',
  'item_blades_of_attack',
  'item_chainmail',
  'item_quarterstaff',
  'item_helm_of_iron_will',
  'item_broadsword',
  'item_claymore',
  'item_javelin',
  'item_mithril_hammer',
  'item_ring_of_protection',
  'item_stout_shield',
  'item_quelling_blade',
  'item_ring_of_regen',
  'item_sobi_mask',
  'item_boots',
  'item_gloves',
  'item_cloak',
  'item_gem',
  'item_magic_stick',
  'item_ring_of_health',
  'item_void_stone',
  'item_energy_booster',
  'item_vitality_booster',
  'item_point_booster',
  'item_platemail',
  'item_talisman_of_evasion',
  'item_hyperstone',
  'item_ultimate_orb',
  'item_demon_edge',
  'item_mystic_staff',
  'item_reaver',
  'item_eagle',
  'item_relic',
  'item_recipe',
  'item_blight_stone',
  'item_wind_lace',
  'item_infused_raindrop',
  'item_orb_of_venom',
  'item_fluffy_hat',
  'item_crown',
  'item_diadem',
]);

export function isNotableItem(name: string): boolean {
  if (!name) return false;
  if (CONSUMABLES.has(name)) return false;
  if (COMPONENTS.has(name)) return false;
  if (name.startsWith('item_recipe')) return false;
  return true;
}
